Vent valves added VVC:04 and VVC:05 with interlock on VVC:05
pcdshub/lcls-plc-las-bts pull request #16
Opened 2024-03-05 23:27 UTC by divyak1910

## Description

## Motivation and Context

## How Has This Been Tested?

## Where Has This Been Documented?

## Screenshots (if appropriate):

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

2024-07-10 14:27 UTC, slactjohnson commented
@divyak1910 Is this PR going to have the BTPS additions as well, or will that be a separate PR? I don't see them here.

2024-07-10 21:00 UTC, divyak1910 commented
Hi @slactjohnson I have added the logic for BTPS as well as fixed some linking issues. This is now ready for review

2024-07-10 21:25 UTC, slactjohnson requested changes
A few small changes, but mostly LGTM

2024-07-10 21:25 UTC, slactjohnson commented on iocBoot/ioc-las-bts/envPaths
This will need to be fixed when we build on psbuild-rhel7

2024-07-10 21:25 UTC, slactjohnson commented on lcls-plc-las-bts/las_bts/GVLs/GVL_BTPS.TcGVL
> +        LAS:BTS:MCS2:01:m13
All of these should have the same IOC and happi database naming pattern (content in the parenthesis).

2024-07-10 21:25 UTC, slactjohnson commented on lcls-plc-las-bts/las_bts/GVLs/GVL_BTPS.TcGVL
> +        LAS:BTS:MCS2:01:m13
Same comment for rotary and goniometer below

2024-07-10 21:25 UTC, slactjohnson commented on lcls-plc-las-bts/las_bts/POUs/PRG_VALVES.TcPOU
> +fb_VP_VVC_4.M_Set_OPN_SW(value := (fb_VP_VVC_2.iq_stValve.q_xOPN_DO OR fb_VP_VVC_1.iq_stValve.q_xOPN_DO )); // Open when Slow vent or N21 purge valve is OPEN
This matches what Conner asked for, but I don't think this is actually what he wants

2024-07-10 21:27 UTC, divyak1910 commented on lcls-plc-las-bts/las_bts/GVLs/GVL_BTPS.TcGVL
> +        LAS:BTS:MCS2:01:m13
Sounds Good. I will make these changes and push the code after the initial test

2024-07-15 16:15 UTC, slactjohnson approved these changes

2024-07-15 16:16 UTC, merged