Turbo Isolation Valve Logic
pcdshub/lcls-plc-las-bts pull request #17
Opened 2024-07-29 23:28 UTC by divyak1910

- Updated Turbo Isolation valve logic

## Description

## Motivation and Context

## How Has This Been Tested?

## Where Has This Been Documented?

## Screenshots (if appropriate):

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive comments
- [ ] Test suite passes locally
- [ ] Libraries are set to fixed versions and not ``Always Newest``
- [ ] Code committed with ``pre-commit`` (alternatively ``pre-commit run --all-files``)

2024-07-31 14:59 UTC, slactjohnson requested changes
A few comments on the code. I'm still not comfortable merging this until we've resolved the TMC file issue.

2024-07-31 14:59 UTC, slactjohnson commented on lcls-plc-las-bts/las_bts/POUs/PRG_VALVES.TcPOU
> +IF (fb_PP_PMF.q_stPump.eState <> E_PumpState.pumpRUNNING) THEN		// IF Roughing Pump is NOT stopped
The comment needs to be updated to reflect the logic

2024-07-31 14:59 UTC, slactjohnson commented on lcls-plc-las-bts/las_bts/POUs/PRG_VALVES.TcPOU
> +IF (fb_PP_PMF.q_stPump.eState = E_PumpState.pumpSTOPPING) THEN
Have you examined the pump state machine to make sure that we will enter this state in an off-normal event, e.g. an error?

2024-07-31 14:59 UTC, slactjohnson commented on lcls-plc-las-bts/las_bts/POUs/PRG_VALVES.TcPOU
> +//fb_PP_VRC_4(
Why is this commented out? If it's not needed, should it be removed?

2024-08-08 19:15 UTC, closed without merging

2024-08-08 19:15 UTC, divyak1910 commented
Older branch , New pull request created with all updates